# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_seat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seat',
            new_name='seats',
        ),
    ]
