# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170419_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seats',
            new_name='seat',
        ),
    ]
