# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170419_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='seat_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
